package com.reader.shared

import com.reader.shared.data.api.CommentOrMore
import com.reader.shared.domain.model.Account
import com.reader.shared.domain.model.Comment
import com.reader.shared.domain.model.CommentSort
import com.reader.shared.domain.model.FlairRichtext
import com.reader.shared.domain.model.GalleryData
import com.reader.shared.domain.model.GalleryItem
import com.reader.shared.domain.model.ImageSource
import com.reader.shared.domain.model.InboxFilter
import com.reader.shared.domain.model.Listing
import com.reader.shared.domain.model.Media
import com.reader.shared.domain.model.Message
import com.reader.shared.domain.model.MessageType
import com.reader.shared.domain.model.MoreComments
import com.reader.shared.domain.model.Post
import com.reader.shared.domain.model.PostSort
import com.reader.shared.domain.model.Preview
import com.reader.shared.domain.model.PreviewImage
import com.reader.shared.domain.model.RedditVideo
import com.reader.shared.domain.model.SearchSort
import com.reader.shared.domain.model.Subreddit
import com.reader.shared.domain.model.TimeFilter
import com.reader.shared.domain.model.User
import com.reader.shared.domain.model.UserSubreddit

fun createTestPost(
    id: String = "abc123",
    name: String = "t3_abc123",
    title: String = "Test Post Title",
    author: String = "testuser",
    subreddit: String = "testsubreddit",
    subredditId: String = "t5_test",
    selfText: String? = null,
    selfTextHtml: String? = null,
    url: String = "https://example.com",
    permalink: String = "/r/testsubreddit/comments/abc123/test_post/",
    thumbnail: String? = null,
    thumbnailWidth: Int? = null,
    thumbnailHeight: Int? = null,
    preview: Preview? = null,
    score: Int = 100,
    upvoteRatio: Float = 0.95f,
    numComments: Int = 50,
    created: Long = 1700000000L,
    createdUtc: Long = 1700000000L,
    isNsfw: Boolean = false,
    isSpoiler: Boolean = false,
    isStickied: Boolean = false,
    isLocked: Boolean = false,
    isArchived: Boolean = false,
    isSaved: Boolean = false,
    isHidden: Boolean = false,
    likes: Boolean? = null,
    domain: String = "example.com",
    postHint: String? = null,
    linkFlairText: String? = null,
    linkFlairBackgroundColor: String? = null,
    linkFlairTextColor: String? = null,
    authorFlairText: String? = null,
    distinguished: String? = null,
    media: Media? = null,
    galleryData: GalleryData? = null,
    crosspostParent: String? = null,
    isCrosspost: Boolean = false,
) = Post(
    id = id,
    name = name,
    title = title,
    author = author,
    subreddit = subreddit,
    subredditId = subredditId,
    selfText = selfText,
    selfTextHtml = selfTextHtml,
    url = url,
    permalink = permalink,
    thumbnail = thumbnail,
    thumbnailWidth = thumbnailWidth,
    thumbnailHeight = thumbnailHeight,
    preview = preview,
    score = score,
    upvoteRatio = upvoteRatio,
    numComments = numComments,
    created = created,
    createdUtc = createdUtc,
    isNsfw = isNsfw,
    isSpoiler = isSpoiler,
    isStickied = isStickied,
    isLocked = isLocked,
    isArchived = isArchived,
    isSaved = isSaved,
    isHidden = isHidden,
    likes = likes,
    domain = domain,
    postHint = postHint,
    linkFlairText = linkFlairText,
    linkFlairBackgroundColor = linkFlairBackgroundColor,
    linkFlairTextColor = linkFlairTextColor,
    authorFlairText = authorFlairText,
    distinguished = distinguished,
    media = media,
    galleryData = galleryData,
    crosspostParent = crosspostParent,
    isCrosspost = isCrosspost,
)

fun createTestComment(
    id: String = "comment1",
    name: String = "t1_comment1",
    parentId: String = "t3_abc123",
    linkId: String = "t3_abc123",
    author: String = "commenter",
    body: String = "Test comment body",
    bodyHtml: String = "<p>Test comment body</p>",
    score: Int = 10,
    created: Long = 1700000100L,
    createdUtc: Long = 1700000100L,
    isSubmitter: Boolean = false,
    distinguished: String? = null,
    isStickied: Boolean = false,
    isLocked: Boolean = false,
    isArchived: Boolean = false,
    isSaved: Boolean = false,
    isCollapsed: Boolean = false,
    likes: Boolean? = null,
    depth: Int = 0,
    replies: List<Comment> = emptyList(),
    moreReplies: MoreComments? = null,
    authorFlairText: String? = null,
    authorFlairBackgroundColor: String? = null,
    authorFlairRichtext: List<FlairRichtext> = emptyList(),
    scoreHidden: Boolean = false,
    edited: Long? = null,
    subreddit: String = "testsubreddit",
    permalink: String = "/r/testsubreddit/comments/abc123/test/comment1/",
) = Comment(
    id = id,
    name = name,
    parentId = parentId,
    linkId = linkId,
    author = author,
    body = body,
    bodyHtml = bodyHtml,
    score = score,
    created = created,
    createdUtc = createdUtc,
    isSubmitter = isSubmitter,
    distinguished = distinguished,
    isStickied = isStickied,
    isLocked = isLocked,
    isArchived = isArchived,
    isSaved = isSaved,
    isCollapsed = isCollapsed,
    likes = likes,
    depth = depth,
    replies = replies,
    moreReplies = moreReplies,
    authorFlairText = authorFlairText,
    authorFlairBackgroundColor = authorFlairBackgroundColor,
    authorFlairRichtext = authorFlairRichtext,
    scoreHidden = scoreHidden,
    edited = edited,
    subreddit = subreddit,
    permalink = permalink,
)

fun createTestSubreddit(
    id: String = "sub1",
    name: String = "t5_sub1",
    displayName: String = "testsubreddit",
    displayNamePrefixed: String = "r/testsubreddit",
    title: String = "Test Subreddit",
    description: String? = "A test subreddit",
    descriptionHtml: String? = null,
    publicDescription: String? = "Public description",
    subscribers: Long = 100000L,
    activeUserCount: Int? = 500,
    created: Long = 1600000000L,
    createdUtc: Long = 1600000000L,
    isNsfw: Boolean = false,
    isSubscribed: Boolean = false,
    isFavorite: Boolean = false,
    iconUrl: String? = null,
    bannerUrl: String? = null,
    communityIcon: String? = null,
    primaryColor: String? = null,
    keyColor: String? = null,
    url: String = "/r/testsubreddit/",
    subredditType: String = "public",
    allowImages: Boolean = true,
    allowVideos: Boolean = true,
    allowPolls: Boolean = true,
    spoilersEnabled: Boolean = true,
    userIsModerator: Boolean = false,
    userIsBanned: Boolean = false,
    userIsContributor: Boolean = false,
    userIsMuted: Boolean = false,
) = Subreddit(
    id = id,
    name = name,
    displayName = displayName,
    displayNamePrefixed = displayNamePrefixed,
    title = title,
    description = description,
    descriptionHtml = descriptionHtml,
    publicDescription = publicDescription,
    subscribers = subscribers,
    activeUserCount = activeUserCount,
    created = created,
    createdUtc = createdUtc,
    isNsfw = isNsfw,
    isSubscribed = isSubscribed,
    isFavorite = isFavorite,
    iconUrl = iconUrl,
    bannerUrl = bannerUrl,
    communityIcon = communityIcon,
    primaryColor = primaryColor,
    keyColor = keyColor,
    url = url,
    subredditType = subredditType,
    allowImages = allowImages,
    allowVideos = allowVideos,
    allowPolls = allowPolls,
    spoilersEnabled = spoilersEnabled,
    userIsModerator = userIsModerator,
    userIsBanned = userIsBanned,
    userIsContributor = userIsContributor,
    userIsMuted = userIsMuted,
)

fun createTestUser(
    id: String = "user1",
    name: String = "testuser",
    created: Long = 1500000000L,
    createdUtc: Long = 1500000000L,
    linkKarma: Int = 1000,
    commentKarma: Int = 5000,
    totalKarma: Int = 6000,
    iconUrl: String? = null,
    bannerUrl: String? = null,
    isGold: Boolean = false,
    isMod: Boolean = false,
    isVerified: Boolean = true,
    hasVerifiedEmail: Boolean = true,
    isSuspended: Boolean = false,
    isEmployee: Boolean = false,
    subreddit: UserSubreddit? = null,
) = User(
    id = id,
    name = name,
    created = created,
    createdUtc = createdUtc,
    linkKarma = linkKarma,
    commentKarma = commentKarma,
    totalKarma = totalKarma,
    iconUrl = iconUrl,
    bannerUrl = bannerUrl,
    isGold = isGold,
    isMod = isMod,
    isVerified = isVerified,
    hasVerifiedEmail = hasVerifiedEmail,
    isSuspended = isSuspended,
    isEmployee = isEmployee,
    subreddit = subreddit,
)

fun createTestAccount(
    id: String = "acc1",
    name: String = "testuser",
    created: Long = 1500000000L,
    createdUtc: Long = 1500000000L,
    linkKarma: Int = 1000,
    commentKarma: Int = 5000,
    totalKarma: Int = 6000,
    iconUrl: String? = null,
    inboxCount: Int = 0,
    hasMail: Boolean = false,
    hasModMail: Boolean = false,
    isGold: Boolean = false,
    isMod: Boolean = false,
    numFriends: Int = 0,
    over18: Boolean = false,
    prefNightMode: Boolean = false,
    prefShowNsfw: Boolean = false,
    prefNoProfanity: Boolean = false,
) = Account(
    id = id,
    name = name,
    created = created,
    createdUtc = createdUtc,
    linkKarma = linkKarma,
    commentKarma = commentKarma,
    totalKarma = totalKarma,
    iconUrl = iconUrl,
    inboxCount = inboxCount,
    hasMail = hasMail,
    hasModMail = hasModMail,
    isGold = isGold,
    isMod = isMod,
    numFriends = numFriends,
    over18 = over18,
    prefNightMode = prefNightMode,
    prefShowNsfw = prefShowNsfw,
    prefNoProfanity = prefNoProfanity,
)

fun createTestMessage(
    id: String = "msg1",
    name: String = "t4_msg1",
    author: String? = "sender",
    dest: String = "testuser",
    subject: String = "Test Subject",
    body: String = "Test message body",
    bodyHtml: String = "<p>Test message body</p>",
    created: Long = 1700000000L,
    createdUtc: Long = 1700000000L,
    isNew: Boolean = false,
    wasComment: Boolean = false,
    context: String? = null,
    subreddit: String? = null,
    parentId: String? = null,
    firstMessageName: String? = null,
    replies: List<Message> = emptyList(),
    type: MessageType = MessageType.PRIVATE_MESSAGE,
    linkTitle: String? = null,
    likes: Boolean? = null,
) = Message(
    id = id,
    name = name,
    author = author,
    dest = dest,
    subject = subject,
    body = body,
    bodyHtml = bodyHtml,
    created = created,
    createdUtc = createdUtc,
    isNew = isNew,
    wasComment = wasComment,
    context = context,
    subreddit = subreddit,
    parentId = parentId,
    firstMessageName = firstMessageName,
    replies = replies,
    type = type,
    linkTitle = linkTitle,
    likes = likes,
)

fun createTestMoreComments(
    id: String = "more1",
    name: String = "t1_more1",
    parentId: String = "t1_comment1",
    count: Int = 5,
    depth: Int = 1,
    children: List<String> = listOf("child1", "child2", "child3"),
) = MoreComments(
    id = id,
    name = name,
    parentId = parentId,
    count = count,
    depth = depth,
    children = children,
)

fun <T> createTestListing(
    items: List<T> = emptyList(),
    after: String? = null,
    before: String? = null,
    dist: Int? = null,
) = Listing(
    items = items,
    after = after,
    before = before,
    dist = dist,
)
